/* Estilos Reset Básico */ body { margin: 0; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: white; background-color: #000; overflow-x: hidden; }

{ margin: 0; padding: 0; box-sizing: border-box; } html { scroll-behavior: smooth; } 

/* Classes base para as seções de altura total */ .full-height-section { position: relative; width: 100vw; height: 100vh; display: flex; justify-content: center; align-items: center; overflow: hidden; }

/* Seção 1: Vídeo de Fundo */ .hero-section-1 video#video-background-1 { position: absolute; top: 50%; left: 50%; min-width: 100%; min-height: 100%; width: auto; height: auto; z-index: -1; transform: translate(-50%, -50%); object-fit: cover; } .hero-section-1 .hero-content { text-align: center; z-index: 1; } .hero-section-1 .hero-content .slogan-main { font-family: 'Playfair Display', serif; font-size: 3rem; font-weight: 700; margin-bottom: 0.5em; } .hero-section-1 .hero-content .slogan-sub { font-size: 1.5rem; font-weight: 300; margin-bottom: 1em; } .hero-section-1 .hero-content .btn { padding: 0.75em 1.5em; font-size: 1rem; text-decoration: none; color: white; background-color: #CC0000; border-radius: 4px; transition: background-color 0.3s; } .hero-section-1 .hero-content .btn:hover { background-color: #AA0000; }

/* Seção 2: Minimalista */ .secao-minimalista-2 .container { display: flex; justify-content: space-between; align-items: center; width: 80%; margin: 0 auto; } .neo-texto { font-family: 'EB Garamond', serif; font-size: 1.25rem; line-height: 1.6; color: #EEE; } .neo-texto .highlight-global { color: #00CCCC; font-weight: 700; } .linha-divisoria { width: 2px; height: 60%; background-color: #444; }

/* Seção 3: Outro Vídeo de Fundo */ .hero-section-3 .video-background-3 { position: absolute; top: 50%; left: 50%; min-width: 100%; min-height: 100%; transform: translate(-50%, -50%); object-fit: cover; z-index: -1; } .hero-section-3 .overlay-3 { position: relative; text-align: center; z-index: 1; color: white; padding: 0 2rem; } .hero-section-3 .overlay-3 h1 { font-family: 'Montserrat', sans-serif; font-size: 3rem; text-transform: uppercase; margin-bottom: 0.5em; } .hero-section-3 .overlay-3 p { font-size: 1.25rem; margin-bottom: 1em; } .hero-section-3 .overlay-3 .botao { padding: 0.75em 1.5em; font-size: 1rem; border: none; cursor: pointer; background-color: #00CCCC; color: #000; border-radius: 4px; transition: background-color 0.3s; } .hero-section-3 .overlay-3 .botao:hover { background-color: #00AAAA; }

/* Seção 4: Canvas e Texto */ .secao-octahedrons-4 .center-text { position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); text-align: center; z-index: 1; color: white; } .secao-octahedrons-4 .center-text h1 { font-family: 'Outfit', sans-serif; font-size: 3rem; margin-bottom: 0.5em; } .secao-octahedrons-4 .center-text p { font-size: 1.25rem; margin-bottom: 1em; } .secao-octahedrons-4 .center-text .cta-button { padding: 0.75em 1.5em; font-size: 1rem; cursor: pointer; background-color: #CC0000; color: white; border: none; border-radius: 4px; transition: background-color 0.3s; } .secao-octahedrons-4 .center-text .cta-button:hover { background-color: #AA0000; } .secao-octahedrons-4 canvas#bg-canvas-4 { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }

/* Seção 5: Estilos Vídeo, Overlay e Conteúdo */ .hero-section-5 { position: relative; width: 100vw; height: 100vh; } .hero-section-5 .video-container-5 { position: absolute; top: 0; left: 0; width: 100%; height: 100%; overflow: hidden; } .hero-section-5 video.video-bg-5 { position: absolute; top: 50%; left: 50%; min-width: 100%; min-height: 100%; transform: translate(-50%, -50%); object-fit: cover; } .hero-section-5 .overlay-5 { position: absolute; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0, 0, 0, 0.5); } .hero-section-5 .transition-overlay-5 { position: absolute; width: 100%; height: 100%; background: rgba(255, 255, 255, 0.1); animation: fadeIn 5s infinite; } .hero-section-5 .logo-5 { position: absolute; top: 50px; left: 50px; font-family: 'Outfit', sans-serif; font-size: 1.5rem; color: white; text-decoration: none; z-index: 1; } .hero-section-5 .social-links-5 { position: absolute; top: 50px; right: 50px; display: flex; gap: 1rem; z-index: 1; } .hero-section-5 .social-links-5 a { color: white; font-size: 1.25rem; transition: color 0.3s; } .hero-section-5 .social-links-5 a:hover { color: #00CCCC; } .hero-section-5 .scrolldown-5 { position: absolute; bottom: 30px; left: 50%; transform: translateX(-50%); display: flex; flex-direction: column; gap: 5px; z-index: 1; } .hero-section-5 .scrolldown-5 span { width: 3px; height: 30px; background: white; display: block; animation: scrollDown 2s infinite; } .hero-section-5 .content-5 { position: relative; z-index: 1; text-align: center; max-width: 80%; margin: 0 auto; } .hero-section-5 .content-5 h1 { font-family: 'Montserrat', sans-serif; font-size: 4rem; margin-bottom: 0.5rem; opacity: 0; animation: fadeInUp 1s forwards; } .hero-section-5 .content-5 .subtitle-5 { font-family: 'Playfair Display', serif; font-size: 1.25rem; letter-spacing: 6px; text-transform: uppercase; margin-bottom: 1rem; opacity: 0; animation: fadeInUp 1s 0.5s forwards; } .hero-section-5 .content-5 .message-5 { font-size: 1.25rem; opacity: 0; animation: fadeInUp 1s 1s forwards; } .hero-section-5 .content-5.second-take { display: none; }

/* Animações */ @keyframes fadeIn { 0% { opacity: 0; } 100% { opacity: 1; } } @keyframes fadeInUp { 0% { opacity: 0; transform: translateY(20px); } 100% { opacity: 1; transform: translateY(0); } } @keyframes scrollDown { 0%, 20%, 50%, 80%, 100% { transform: translateY(0); } 40% { transform: translateY(10px); } 60% { transform: translateY(5px); } }

/* Responsivo */ @media (max-width: 768px) { .hero-section-1 .hero-content .slogan-main { font-size: 2.5rem; } .hero-section-3 .overlay-3 h1 { font-size: 2rem; } .hero-section-5 .content-5 h1 { font-size: 3rem; } .hero-section-5 .subtitle-5 { font-size: 1rem; letter-spacing: 4px; } }

@media (max-width: 480px) { .hero-section-1 .hero-content .slogan-main { font-size: 2rem; } .hero-section-3 .overlay-3 h1 { font-size: 1.5rem; } .hero-section-5 .content-5 h1 { font-size: 2rem; } .hero-sectional-5 .subtitle-5 { font-size: 0.9rem; letter-spacing: 3px; } }

